language: generic
group: travis_latest

git:
  depth: 3
  quiet: true

os:
- linux
- osx

env: FC=gfortran-6

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gfortran-6

before_install:
- if [[ $TRAVIS_OS_NAME == osx ]]; then
  brew update > /dev/null;
  brew install gcc > /dev/null || brew link --overwrite gcc > /dev/null;
  export FC=gfortran;
  fi

install:
- cd bin
- cmake ..
- cmake --build .

script: ctest -V

