# gfortran >= 6
language: c
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

env: FC=gfortran

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages:
    - gfortran-6

matrix:
  include:
  - os: linux
    env: FC=gfortran-6
  - os: windows
    install:
    - cd $TRAVIS_BUILD_DIR/build
    - cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" ..

install:
- cd $TRAVIS_BUILD_DIR/build

script:
- cmake -Drealbits=32 ..
- cmake --build .
- ctest --output-on-failure

- cmake -Drealbits=64 ..
- cmake --build .
- ctest --output-on-failure


