# gfortran >= 5
language: c
group: travis_latest
dist: xenial

git:
  depth: 3
  quiet: true

env: FC=gfortran

addons:
  apt:
    packages:
    - gfortran

matrix:
  include:
  - os: linux
#  - os: osx
#    before_install:
#    - brew install gcc > /dev/null
  - os: windows
    install: 
    - cd bin
    - cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" ..
    - cmake --build .

install: cd bin

script:
- cmake -Drealbits=32 ..
- cmake --build .
- ctest --output-on-failure

- cmake -Drealbits=64 ..
- cmake --build .
- ctest --output-on-failure


