image:
- Visual Studio 2017
- ubuntu1804

environment:
  MINGW_DIR: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin

clone_depth: 25

build: off

init:
- cmd: set PATH=%MINGW_DIR%;%PATH%

install:
- cmd: cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" -B build
- sh: cmake -B build
- cmake --build build --parallel

test_script:
- cd build
- ctest --parallel --output-on-failure
