# gfortran >= 6
language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

env: FC=gfortran-6

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages:
    - gfortran-6

matrix:
  include:
  - os: linux
    env: FC=gfortran-6
    script:
    - meson setup -Drealbits=32 build
    - meson test -C build
  - os: linux
    env: FC=gfortran-6
    script:
    - meson setup -Drealbits=64 build
    - meson test -C build

before_install:
- git -C $HOME clone https://github.com/mesonbuild/meson
- python -m pip install -e $HOME/meson
- curl -Ls https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip -o ninja-linux.zip
- sudo unzip ninja-linux.zip -d /usr/local/bin/
