if(CMAKE_Fortran_COMPILER_ID STREQUAL Intel)
  if(NOT WIN32)
    set(CMAKE_Fortran_FLAGS "-stand f18 -traceback -warn -heap-arrays ")
  else()
    set(CMAKE_Fortran_FLAGS "/stand:f18 /traceback /warn /heap-arrays ")
  endif()
elseif(CMAKE_Fortran_COMPILER_ID STREQUAL GNU)
  if(CMAKE_Fortran_COMPILER_VERSION VERSION_GREATER_EQUAL 8)
    string(APPEND CMAKE_Fortran_FLAGS "-std=f2018 ")
  endif()

  string(APPEND CMAKE_Fortran_FLAGS "-fimplicit-none -march=native -Wall -Wextra ")
  set(CMAKE_Fortran_FLAGS_DEBUG "-ffpe-trap=overflow -Warray-bounds ")
elseif(CMAKE_Fortran_COMPILER_ID STREQUAL PGI)
  set(CMAKE_Fortran_FLAGS "-C -Mdclchk ")
elseif(CMAKE_Fortran_COMPILER_ID STREQUAL NAG)
  set(CMAKE_Fortran_FLAGS "-f2018 -C -colour -gline -nan -info -u ")
endif()
