name: ci

on:
  push:
    paths:
      - "**/*.f90"
      - "**/*.cmake"
      - "**/CMakeLists.txt"


jobs:

  meson:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - run: pip install meson ninja

    - run: meson setup build
    - run: meson compile -C build
    - run: meson test -C build -v


  cmake:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        bits: [64, 32]

    steps:
    - uses: actions/checkout@v3

    - run: cmake --preset default -Drealbits=${{ matrix.bits }}

    - name: test workflow
      run: cmake --workflow --preset default
