name: ci

env:
  CMAKE_BUILD_TYPE: Release

on:
  push:
    paths:
      - "**/*.f90"
      - "**/*.cmake"
      - "**/CMakeLists.txt"


jobs:

  meson:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: pip install meson ninja

    - run: meson setup build

    - run: meson test -C build -v


  cmake:
    strategy:
      matrix:
        bits: [64, 32]
        cfg: [{os: ubuntu-latest, gen: "Unix Makefiles"},
              {os: windows-latest, gen: "MinGW Makefiles"}]

    runs-on: ${{ matrix.cfg.os }}

    steps:
    - uses: actions/checkout@v2

    - run: cmake -B build -Drealbits=${{ matrix.bits }} -G "${{ matrix.cfg.gen }}"
    - run: cmake --build build
    - run: ctest --test-dir build --preset default
